import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/Link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BatBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/batman.svg" />
      </Head>
      <main>
        <nav className={styles.navigation}>
          <ul>
            <div className="links"><Link href="/" ><li>Home</li></Link></div>
            <div className="links"><Link href="/about"><li>About</li></Link></div>
            <div className="links"><Link href="/blogs"><li>Blogs</li></Link></div>
            <div className="links"><Link href="/contact"><li>Contact the Bat</li></Link></div>
          </ul>
        </nav>

        <div className={styles.heading}>
          <h1>Bat Blogs</h1>
        </div>

        <div className={styles.image}>
          <Image
            src="/batman-logo.svg"
            alt="batman Logo"
            width={500}
            height={220}
            priority
          />
        </div>

        <div className={styles.blogs}>
          <h4>Blogs go here</h4>
        </div>
      </main>
    </div>

  );
}
