import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

const StyledHome = styled.div`
  display: flex;
  flex-direction: column;

  .navigation {
    display: flex;
    justify-content: center;
  }

  .navigation ul {
    margin-top: 1rem;
    display: flex;
  }

  .navigation li {
    list-style: none;
    margin: 0 1.5rem;
    font-weight: bold;
    font-size: 1.3rem;
  }

  .heading {
    display: flex;
    justify-content: center;
  }

  .image {
    display: flex;
    justify-content: center;
  }
`;

export default function Home() {
  return (
    <StyledHome>
      <Head>
        <title>BatBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/batman.svg" />
      </Head>
      <main>
        <nav className="navigation">
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Blogs</li>
            <li>Contact the Bat</li>
          </ul>
        </nav>

        <div className="heading">
          <h1>Bat Blogs</h1>
        </div>

        <div className="image">
          <Image
            src="/batman-logo.svg"
            alt="batman Logo"
            width={500}
            height={220}
            priority
          />
        </div>

        <div>
          <h4>Blogs</h4>
        </div>
      </main>
    </StyledHome>
  );
}
